### PR TITLE
Add permission to read its own config file

### PR DESCRIPTION
**Pull request by pesader**

### CODE REVIEW

**Comment by thorpelawrence** [comment]
Good catch, thanks!

**Comment by thorpelawrence** [comment]
Actually thinking about it, we should probably just use the sandboxed config where possible as Flatpak suggests, did you have a specific use case for using the non-sandboxed config file?

**Comment by pesader** [comment]
I had ncspot installed using cargo before, and thought it would be nice to use the same config.

> We should probably just use the sandboxed config where possible as Flatpak suggests.

I didn't know we had the option to have a "sandboxed config" though! Perhaps a better solution than this PR is to update the ncspot README to mention the location of the config file in case it is installed as a flatpak (which I can do :).

**Comment by thorpelawrence** [comment]
Yeah sorry, my bad, should have checked the test build before merging. I do unfortunately get this error when starting anyway, so I'll revert

```
$ flatpak run io.github.hrkfdn.ncspot                                                               
could not load config: Failed writing content to /home/lawrence/.var/app/io.github.hrkfdn.ncspot/config/ncspot/config.toml: No such file or directory (os error 2)
```

**Comment by thorpelawrence** [comment]
The location of the config is also shown at the top of the `?` menu in ncspot (well, it shows it as keybindings but same thing). On my machine for example it's `~/.var/app/io.github.hrkfdn.ncspot/config/ncspot/config.toml`

**Comment by pesader** [comment]
> The location of the config is also shown at the top of the ? menu in ncspot

Never knew that!

Anyways, sorry for wasting your time on this and thanks for maintaining this package. It's made installing `ncspot` a lot easier over on Fedora Silverblue.

Cheers!

**Pull request merged**
